<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-03-16 01:17

import api.models
=======
# Generated by Django 5.1.7 on 2025-03-14 22:27

>>>>>>> main
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=api.models.generate_unique_code,
                        max_length=8,
                        unique=True,
                    ),
                ),
                ("host", models.CharField(max_length=100, unique=True)),
                ("guest_can_pause", models.BooleanField(default=False)),
                ("votes_to_skip", models.IntegerField(default=1)),
                ("created_at", models.DateField(auto_now_add=True)),
=======
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='generate_unique_code', max_length=8, unique=True)),
                ('host', models.CharField(max_length=100, unique=True)),
                ('guest_can_pause', models.BooleanField(default=False)),
                ('votes_to_skip', models.IntegerField(default=1)),
                ('created_at', models.DateField(auto_now_add=True)),
>>>>>>> main
            ],
        ),
    ]
